export const GET_BANNER_REQUEST = "GET_BANNER_REQUEST";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAILURE = "GET_BANNER_FAILURE";

export const INITIALIZE_BANNER_REQUEST = "INITIALIZE_BANNER_REQUEST";
export const INITIALIZE_BANNER_SUCCESS = "INITIALIZE_BANNER_SUCCESS";
export const INITIALIZE_BANNER_FAILURE = "INITIALIZE_BANNER_FAILURE";

export const UPDATE_BANNER_REQUEST = "UPDATE_BANNER_REQUEST";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_FAILURE = "UPDATE_BANNER_FAILURE";
