export const GET_TOOLBAR_REQUEST = "GET_TOOLBAR_REQUEST";
export const GET_TOOLBAR_SUCCESS = "GET_TOOLBAR_SUCCESS";
export const GET_TOOLBAR_FAILURE = "GET_TOOLBAR_FAILURE";

export const THEME_INITIALIZE_REQUEST = "THEME_INITIALIZE_REQUEST";
export const THEME_INITIALIZE_SUCCESS = "THEME_INITIALIZE_SUCCESS";
export const THEME_INITIALIZE_FAILURE = "THEME_INITIALIZE_FAILURE";

export const UPDATE_TOOLBAR_REQUEST = "UPDATE_TOOLBAR_REQUEST";
export const UPDATE_TOOLBAR_SUCCESS = "UPDATE_TOOLBAR_SUCCESS";
export const UPDATE_TOOLBAR_FAILURE = "UPDATE_TOOLBAR_FAILURE";

export const GET_THEME_STATUS_REQUEST = "GET_THEME_STATUS_REQUEST";
export const GET_THEME_STATUS_SUCCESS = "GET_THEME_STATUS_SUCCESS";
export const GET_THEME_STATUS_FAILURE = "GET_THEME_STATUS_FAILURE ";
